/**
 * A module to bring the NumPy C SIMD vectorization interface "NPYV" for testing purposes.
 *
 * Please keep this module independent from NumPy array or any other modules,
 * since NPYV intrinsics may be involved in their functionality,
 * which increases the degree of complexity in tracking and detecting errors.
 *
 * TODO: Add an independent sphinx doc.
 *
 * Please go to '_simd.dispatch.c.src', in order to add any new NPYV intrinsics.
 */
#ifndef _SIMD_SIMD_H_
#define _SIMD_SIMD_H_

#include <Python.h>
#include "numpy/npy_common.h"

#ifndef NPY_DISABLE_OPTIMIZATION
// autogenerated, required for CPU dispatch macros
#include "_simd.dispatch.h"
#endif

/**
 * Still needs to provide a module for CPU features that are not supported by NPYV,
 * to add constants for NPY_SIMD, NPY_SIMD_F64, and NPY_SIMD_WIDTH.
 */
NPY_CPU_DISPATCH_DECLARE(NPY_VISIBILITY_HIDDEN PyObject *simd_module_create, (void))

#endif // _SIMD_SIMD_H_
